<?php

/**
* Function to change the author of saved/submitted posts.
* Note: For logged in users submitting a draft form, the post is saved with the user as author.  Therefore changing this will result in the user not being able to reload their draft form.
* @param string $author_id the post author, default is current user if logged in, else site admin.
* @param $cf7_id  the form id being loaded.
* @param array $submitted_data complete set of data submitted in the form as an array of field-name=>value pairs.
* @param string $ckf7_key unique key to identify your form.
* @return string a valid user id.
*/

// function set_post_author($author_id, $cf7_id, $submitted_data, $cf7_key){
// 	$author_id = 1;
// 	return $author_id;
// }
// add_filter('cf7_2_post_author_post', 'set_post_author',10,4);

/**
* Function to change the post status of saved/submitted posts.
* @param string $status the post status, default is 'draft'.
* @param string $ckf7_key unique key to identify your form.
* @param array $submitted_data complete set of data submitted in the form as an array of field-name=>value pairs.
* @return string a valid post status ('publish'|'draft'|'pending'|'trash')
*/
// function publish_new_post($status, $ckf7_key, $submitted_data){
// 	/*The default behaviour is to save post to 'draft' status.  If you wish to change this, you can use this filter and return a valid post status: 'publish'|'draft'|'pending'|'trash'*/
// 	return 'draft';
// }
// add_filter( 'cf7_2_post_status_post', 'publish_new_post',10,3);


function selectData($n, $options, $args) {

	/*[select upcoming-gigs data:gigs]*/

  if (in_array('country', $options)){
    $countryList = countryFields();
    return $countryList;
  }
  return $n;
}
add_filter('wpcf7_form_tag_data_option','selectData',10, 3);

function countryFields(){

	$lang = pll_current_language();

	if($lang == "en"){

		$arrayList = array(
		'AF' => 'Afghanistan',
		'AX' => 'Åland Islands',
		'AL' => 'Albania',
		'DZ' => 'Algeria',
		'AS' => 'American Samoa',
		'AD' => 'Andorra',
		'AO' => 'Angola',
		'AI' => 'Anguilla',
		'AQ' => 'Antarctica',
		'AG' => 'Antigua & Barbuda',
		'AR' => 'Argentina',
		'AM' => 'Armenia',
		'AW' => 'Aruba',
		'AU' => 'Australia',
		'AT' => 'Austria',
		'AZ' => 'Azerbaijan',
		'BS' => 'Bahamas',
		'BH' => 'Bahrain',
		'BD' => 'Bangladesh',
		'BB' => 'Barbados',
		'BY' => 'Belarus',
		'BE' => 'Belgium',
		'BZ' => 'Belize',
		'BJ' => 'Benin',
		'BM' => 'Bermuda',
		'BT' => 'Bhutan',
		'BO' => 'Bolivia',
		'BA' => 'Bosnia & Herzegovina',
		'BW' => 'Botswana',
		'BV' => 'Bouvet Island',
		'BR' => 'Brazil',
		'IO' => 'British Indian Ocean Territory',
		'VG' => 'British Virgin Islands',
		'BN' => 'Brunei',
		'BG' => 'Bulgaria',
		'BF' => 'Burkina Faso',
		'BI' => 'Burundi',
		'KH' => 'Cambodia',
		'CM' => 'Cameroon',
		'CA' => 'Canada',
		'CV' => 'Cape Verde',
		'BQ' => 'Caribbean Netherlands',
		'KY' => 'Cayman Islands',
		'CF' => 'Central African Republic',
		'TD' => 'Chad',
		'CL' => 'Chile',
		'CN' => 'China',
		'CX' => 'Christmas Island',
		'CC' => 'Cocos (Keeling) Islands',
		'CO' => 'Colombia',
		'KM' => 'Comoros',
		'CG' => 'Congo - Brazzaville',
		'CD' => 'Congo - Kinshasa',
		'CK' => 'Cook Islands',
		'CR' => 'Costa Rica',
		'CI' => 'Côte d’Ivoire',
		'HR' => 'Croatia',
		'CU' => 'Cuba',
		'CW' => 'Curaçao',
		'CY' => 'Cyprus',
		'CZ' => 'Czechia',
		'DK' => 'Denmark',
		'DJ' => 'Djibouti',
		'DM' => 'Dominica',
		'DO' => 'Dominican Republic',
		'EC' => 'Ecuador',
		'EG' => 'Egypt',
		'SV' => 'El Salvador',
		'GQ' => 'Equatorial Guinea',
		'ER' => 'Eritrea',
		'EE' => 'Estonia',
		'SZ' => 'Eswatini',
		'ET' => 'Ethiopia',
		'FK' => 'Falkland Islands',
		'FO' => 'Faroe Islands',
		'FJ' => 'Fiji',
		'FI' => 'Finland',
		'FR' => 'France',
		'GF' => 'French Guiana',
		'PF' => 'French Polynesia',
		'TF' => 'French Southern Territories',
		'GA' => 'Gabon',
		'GM' => 'Gambia',
		'GE' => 'Georgia',
		'DE' => 'Germany',
		'GH' => 'Ghana',
		'GI' => 'Gibraltar',
		'GR' => 'Greece',
		'GL' => 'Greenland',
		'GD' => 'Grenada',
		'GP' => 'Guadeloupe',
		'GU' => 'Guam',
		'GT' => 'Guatemala',
		'GG' => 'Guernsey',
		'GN' => 'Guinea',
		'GW' => 'Guinea-Bissau',
		'GY' => 'Guyana',
		'HT' => 'Haiti',
		'HM' => 'Heard & McDonald Islands',
		'HN' => 'Honduras',
		'HK' => 'Hong Kong SAR China',
		'HU' => 'Hungary',
		'IS' => 'Iceland',
		'IN' => 'India',
		'ID' => 'Indonesia',
		'IR' => 'Iran',
		'IQ' => 'Iraq',
		'IE' => 'Ireland',
		'IM' => 'Isle of Man',
		'IL' => 'Israel',
		'IT' => 'Italy',
		'JM' => 'Jamaica',
		'JP' => 'Japan',
		'JE' => 'Jersey',
		'JO' => 'Jordan',
		'KZ' => 'Kazakhstan',
		'KE' => 'Kenya',
		'KI' => 'Kiribati',
		'KW' => 'Kuwait',
		'KG' => 'Kyrgyzstan',
		'LA' => 'Laos',
		'LV' => 'Latvia',
		'LB' => 'Lebanon',
		'LS' => 'Lesotho',
		'LR' => 'Liberia',
		'LY' => 'Libya',
		'LI' => 'Liechtenstein',
		'LT' => 'Lithuania',
		'LU' => 'Luxembourg',
		'MO' => 'Macao SAR China',
		'MG' => 'Madagascar',
		'MW' => 'Malawi',
		'MY' => 'Malaysia',
		'MV' => 'Maldives',
		'ML' => 'Mali',
		'MT' => 'Malta',
		'MH' => 'Marshall Islands',
		'MQ' => 'Martinique',
		'MR' => 'Mauritania',
		'MU' => 'Mauritius',
		'YT' => 'Mayotte',
		'MX' => 'Mexico',
		'FM' => 'Micronesia',
		'MD' => 'Moldova',
		'MC' => 'Monaco',
		'MN' => 'Mongolia',
		'ME' => 'Montenegro',
		'MS' => 'Montserrat',
		'MA' => 'Morocco',
		'MZ' => 'Mozambique',
		'MM' => 'Myanmar (Burma)',
		'NA' => 'Namibia',
		'NR' => 'Nauru',
		'NP' => 'Nepal',
		'NL' => 'Netherlands',
		'NC' => 'New Caledonia',
		'NZ' => 'New Zealand',
		'NI' => 'Nicaragua',
		'NE' => 'Niger',
		'NG' => 'Nigeria',
		'NU' => 'Niue',
		'NF' => 'Norfolk Island',
		'KP' => 'North Korea',
		'MK' => 'North Macedonia',
		'MP' => 'Northern Mariana Islands',
		'NO' => 'Norway',
		'OM' => 'Oman',
		'PK' => 'Pakistan',
		'PW' => 'Palau',
		'PS' => 'Palestinian Territories',
		'PA' => 'Panama',
		'PG' => 'Papua New Guinea',
		'PY' => 'Paraguay',
		'PE' => 'Peru',
		'PH' => 'Philippines',
		'PN' => 'Pitcairn Islands',
		'PL' => 'Poland',
		'PT' => 'Portugal',
		'PR' => 'Puerto Rico',
		'QA' => 'Qatar',
		'RE' => 'Réunion',
		'RO' => 'Romania',
		'RU' => 'Russia',
		'RW' => 'Rwanda',
		'WS' => 'Samoa',
		'SM' => 'San Marino',
		'ST' => 'São Tomé & Príncipe',
		'SA' => 'Saudi Arabia',
		'SN' => 'Senegal',
		'RS' => 'Serbia',
		'SC' => 'Seychelles',
		'SL' => 'Sierra Leone',
		'SG' => 'Singapore',
		'SX' => 'Sint Maarten',
		'SK' => 'Slovakia',
		'SI' => 'Slovenia',
		'SB' => 'Solomon Islands',
		'SO' => 'Somalia',
		'ZA' => 'South Africa',
		'GS' => 'South Georgia & South Sandwich Islands',
		'KR' => 'South Korea',
		'SS' => 'South Sudan',
		'ES' => 'Spain',
		'LK' => 'Sri Lanka',
		'BL' => 'St. Barthélemy',
		'SH' => 'St. Helena',
		'KN' => 'St. Kitts & Nevis',
		'LC' => 'St. Lucia',
		'MF' => 'St. Martin',
		'PM' => 'St. Pierre & Miquelon',
		'VC' => 'St. Vincent & Grenadines',
		'SD' => 'Sudan',
		'SR' => 'Suriname',
		'SJ' => 'Svalbard & Jan Mayen',
		'SE' => 'Sweden',
		'CH' => 'Switzerland',
		'SY' => 'Syria',
		'TW' => 'Taiwan',
		'TJ' => 'Tajikistan',
		'TZ' => 'Tanzania',
		'TH' => 'Thailand',
		'TL' => 'Timor-Leste',
		'TG' => 'Togo',
		'TK' => 'Tokelau',
		'TO' => 'Tonga',
		'TT' => 'Trinidad & Tobago',
		'TN' => 'Tunisia',
		'TR' => 'Turkey',
		'TM' => 'Turkmenistan',
		'TC' => 'Turks & Caicos Islands',
		'TV' => 'Tuvalu',
		'UM' => 'U.S. Outlying Islands',
		'VI' => 'U.S. Virgin Islands',
		'UG' => 'Uganda',
		'UA' => 'Ukraine',
		'AE' => 'United Arab Emirates',
		'GB' => 'United Kingdom',
		'US' => 'United States',
		'UY' => 'Uruguay',
		'UZ' => 'Uzbekistan',
		'VU' => 'Vanuatu',
		'VA' => 'Vatican City',
		'VE' => 'Venezuela',
		'VN' => 'Vietnam',
		'WF' => 'Wallis & Futuna',
		'EH' => 'Western Sahara',
		'YE' => 'Yemen',
		'ZM' => 'Zambia',
		'ZW' => 'Zimbabwe',
		);
	
	}
	
	if($lang == "ar"){

		$arrayList = array(
		'AF' => 'أفغانستان',
		'AX' => 'جزر أوكلاند',
		'AL' => 'ألبانيا',
		'DZ' => 'الجزائر',
		'AS' => 'ساموا الأمريكية',
		'AD' => 'أندورا',
		'AO' => 'أنغولا',
		'AI' => 'أنغيلا',
		'AQ' => 'أنتاركتيكا',
		'AG' => 'أنتيغوا وبربودا',
		'AR' => 'الأرجنتين',
		'AM' => 'أرمينيا',
		'AW' => 'أروبا',
		'AU' => 'أستراليا',
		'AT' => 'النمسا',
		'AZ' => 'أذربيجان',
		'BS' => 'جزر البهاما',
		'BH' => 'البحرين',
		'BD' => 'بنغلاديش',
		'BB' => 'بربادوس',
		'BY' => 'بيلاروس',
		'BE' => 'بلجيكا',
		'BZ' => 'بليز',
		'BJ' => 'بنن',
		'BM' => 'برمودا',
		'BT' => 'بوتان',
		'BO' => 'بوليفيا',
		'BA' => 'البوسنة والهرسك',
		'BW' => 'بوتسوانا',
		'BV' => 'جزيرة بوفيت',
		'BR' => 'البرازيل',
		'IO' => 'إقليم المحيط الهندي البريطاني',
		'VG' => 'جزر فرجن البريطانية',
		'BN' => 'بروني',
		'BG' => 'بلغاريا',
		'BF' => 'بوركينا فاسو',
		'BI' => 'بوروندي',
		'KH' => 'كمبوديا',
		'CM' => 'الكاميرون',
		'CA' => 'الكاميرون',
		'CV' => 'الرأس الأخضر',
		'BQ' => 'الكاريبي هولندا',
		'KY' => 'جزر كايمان',
		'CF' => 'جمهورية أفريقيا الوسطى',
		'TD' => 'تشاد',
		'CL' => 'شيلي',
		'CN' => 'الصين',
		'CX' => 'جزيرة الكريسماس',
		'CC' => 'جزر كوكوس (كيلينغ)',
		'CO' => 'كولومبيا',
		'KM' => 'جزر القمر',
		'CG' => 'الكونغو-برازافيل',
		'CD' => 'الكونغو-كينشاسا',
		'CK' => 'جزر كوك',
		'CR' => 'كوستاريكا',
		'CI' => 'ساحل العاج',
		'HR' => 'كرواتيا',
		'CU' => 'كوبا',
		'CW' => 'كوراكاو',
		'CY' => 'قبرص',
		'CZ' => 'التشيكية',
		'DK' => 'الدانمرك',
		'DJ' => 'جيبوتي',
		'DM' => 'جيبوتي',
		'DO' => 'الجمهورية الدومينيكية',
		'EC' => 'إكوادور',
		'EG' => 'مصر',
		'SV' => 'السلفادور',
		'GQ' => 'غينيا الاستوائية',
		'ER' => 'إريتريا',
		'EE' => 'إستونيا',
		'SZ' => 'إيسواتيني',
		'ET' => 'إثيوبيا',
		'FK' => 'جزر فوكلاند',
		'FO' => 'جزر فارو',
		'FJ' => 'فيجي',
		'FI' => 'فنلندا',
		'FR' => 'فرنسا',
		'GF' => 'غيانا الفرنسية',
		'PF' => 'بولينيزيا الفرنسية',
		'TF' => 'الأقاليم الجنوبية الفرنسية',
		'GA' => 'غابون',
		'GM' => 'غامبيا',
		'GE' => 'جورجيا',
		'DE' => 'ألمانيا',
		'GH' => 'غانا',
		'GI' => 'جبل طارق',
		'GR' => 'اليونان',
		'GL' => 'غرينلاند',
		'GD' => 'غرينادا',
		'GP' => 'غوادلوب',
		'GU' => 'غوام',
		'GT' => 'غواتيمالا',
		'GG' => 'غيرنسي',
		'GN' => 'غينيا',
		'GW' => 'غينيا-بيساو',
		'GY' => 'غيانا',
		'HT' => 'هايتي',
		'HM' => 'جزر هيرد وماكدونالد',
		'HN' => 'هندوراس',
		'HK' => 'منطقة هونغ كونغ الإدارية الخاصة الصين',
		'HU' => 'هنغاريا',
		'IS' => 'آيسلندا',
		'IN' => 'الهند',
		'ID' => 'إندونيسيا',
		'IR' => 'إيران',
		'IQ' => 'العراق',
		'IE' => 'أيرلندا',
		'IM' => 'جزيرة مان',
		'IL' => 'إسرائيل',
		'IT' => 'إيطاليا',
		'JM' => 'جامايكا',
		'JP' => 'اليابان',
		'JE' => 'جيرسي',
		'JO' => 'الأردن',
		'KZ' => 'كازاخستان',
		'KE' => 'كازاخستان',
		'KI' => 'كيريباس',
		'KW' => 'الكويت',
		'KG' => 'قيرغيزستان',
		'LA' => 'لاوس',
		'LV' => 'لاتفيا',
		'LB' => 'لبنان',
		'LS' => 'ليسوتو',
		'LR' => 'ليبريا',
		'LY' => 'ليبيا',
		'LI' => 'ليختنشتاين',
		'LT' => 'ليتوانيا',
		'LU' => 'لكسمبرغ',
		'MO' => 'منطقة ماكاو الإدارية الخاصة الصين',
		'MG' => 'مدغشقر',
		'MW' => 'ملاوي',
		'MY' => 'ماليزيا',
		'MV' => 'مالديف',
		'ML' => 'مالي',
		'MT' => 'مالطا',
		'MH' => 'جزر مارشال',
		'MQ' => 'مارتينيك',
		'MR' => 'موريتانيا',
		'MU' => 'موريشيوس',
		'YT' => 'مايوت',
		'MX' => 'المكسيك',
		'FM' => 'ميكرونيسيا ',
		'MD' => 'مولدوفا',
		'MC' => 'موناكو',
		'MN' => 'منغوليا',
		'ME' => 'الجبل الأسود',
		'MS' => 'مونتسيرات',
		'MA' => 'المغرب',
		'MZ' => 'موزامبيق',
		'MM' => 'ميانمار (بورما)',
		'NA' => 'ناميبيا',
		'NR' => 'ناورو',
		'NP' => 'نيبال',
		'NL' => 'هولندا',
		'NC' => 'كاليدونيا الجديدة',
		'NZ' => 'نيوزيلندا',
		'NI' => 'نيكاراغوا',
		'NE' => 'النيجر',
		'NG' => 'نيجيريا',
		'NU' => 'نيوي',
		'NF' => 'جزيرة نورفولك',
		'KP' => 'كوريا الشمالية',
		'MK' => 'مقدونيا الشمالية',
		'MP' => 'جزر ماريانا الشمالية',
		'NO' => 'النرويج',
		'OM' => 'عمان',
		'PK' => 'باكستان',
		'PW' => 'بالاو',
		'PS' => 'الأراضي الفلسطينية',
		'PA' => 'بنما',
		'PG' => 'بابوا غينيا الجديدة',
		'PY' => 'باراغواي',
		'PE' => 'بيرو',
		'PH' => 'الفلبين',
		'PN' => 'جزر بيتكيرن',
		'PL' => 'بولندا',
		'PT' => 'البرتغال',
		'PR' => 'بورتوريكو',
		'QA' => 'قطر',
		'RE' => 'رمونيون',
		'RO' => 'رومانيا',
		'RU' => 'روسيا',
		'RW' => 'رواندا',
		'WS' => 'ساموا',
		'SM' => 'سان مارينو',
		'ST' => ' ساو تومي وبرينسيب',
		'SA' => 'المملكة العربية السعودية',
		'SN' => 'السنغال',
		'RS' => 'صربيا',
		'SC' => 'سيشيل',
		'SL' => 'سيراليون',
		'SG' => 'سنغافورة',
		'SX' => 'سانت مارتن',
		'SK' => 'سلوفاكيا',
		'SI' => 'سلوفينيا',
		'SB' => 'جزر سليمان',
		'SO' => 'الصومال',
		'ZA' => 'جنوب أفريقيا',
		'GS' => 'جورجيا الجنوبية وجزر ساندويتش الجنوبية',
		'KR' => 'كوريا الجنوبية',
		'SS' => 'جنوب السودان',
		'ES' => 'إسبانيا',
		'LK' => 'سري لانكا',
		'BL' => 'سانت بارثولوميو',
		'SH' => 'سانت هيلانة',
		'KN' => 'سانت كيتس ونيفيس',
		'LC' => 'سانت لوسيا',
		'MF' => 'سانت مارتن',
		'PM' => 'سانت بيير وميكلون',
		'VC' => 'سانت فنسنت وجزر غرينادين',
		'SD' => 'السودان',
		'SR' => 'سورينام',
		'SJ' => 'سفالبارد وجان ماين',
		'SE' => 'السويد',
		'CH' => 'سويسرا',
		'SY' => 'سوريا',
		'TW' => 'تايوان',
		'TJ' => 'طاجيكستان',
		'TZ' => 'تنزانيا',
		'TH' => 'تايلند',
		'TL' => 'تيمور-ليشتي',
		'TG' => 'توغو',
		'TK' => 'توكيلاو',
		'TO' => 'تونغا',
		'TT' => 'ترينيداد وتوباغو',
		'TN' => 'تونس',
		'TR' => 'تركيا',
		'TM' => 'تركمانستان',
		'TC' => 'جزر تركس وكايكوس',
		'TV' => 'توفالو',
		'UM' => 'جزر الولايات المتحدة النائية',
		'VI' => 'جزر فيرجن الأمريكية',
		'UG' => 'أوغندا',
		'UA' => 'أوكرانيا',
		'AE' => 'الإمارات العربية المتحدة',
		'GB' => 'المملكة المتحدة',
		'US' => 'الولايات المتحدة',
		'UY' => 'أوروغواي',
		'UZ' => 'أوزبكستان',
		'VU' => 'فانواتو',
		'VA' => 'مدينة الفاتيكان',
		'VE' => 'فنزويلا',
		'VN' => 'فيتنام',
		'WF' => 'واليس وفوتونا',
		'EH' => 'الصحراء الغربية',
		'YE' => 'اليمن',
		'ZM' => 'زامبيا',
		'ZW' => 'زمبابوي',		
		);
		
	}

	return $arrayList;
}

